### ISSUE TITLE
non-admin accounts are not able to remove users from the "Moderators" list

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#435] opened 2024-01-17 09:36 UTC
**Preconditions**
Sign in to https://moderator.allizom.org with an admin account.

**Steps to reproduce**
1. Access the https://moderator.allizom.org/event/new page.
2. Add valid data inside the input fields.
3. Add a non-admin account inside the "Moderators" field and create the event.
4. Sign in to https://moderator.allizom.org using the non-admin account used in step 3.
5. Access the posted event from step 3.
6. Delete a username from the "Moderators" field and click the "save" button.
7. Access the the posted event again.

**Expected behavior**
The username removed in step 6 is no longer displayed inside the "Moderators" field.

**Actual behavior**
The username which was removed in step 6 is still displayed inside the "Moderators" field.

**Screencasts**
![removingmoderatorsnonadmin](https://github.com/mozilla/mozmoderator/assets/28087895/ba2f11c5-936a-43d9-b378-3e0c8a926f5d)

**Additional context**
This issue is not reproducible when removing the "Moderators" while signed in with an admin account.
Maybe also related to https://github.com/mozilla/mozmoderator/issues/432

**Comment by akatsoulas** [comment] 2024-02-14 12:39
Closing as duplicate of #437

**Closed by akatsoulas** 2024-02-14 12:39 UTC
