### ISSUE TITLE
Default moderator is removed when creating an event via non-admin account

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/mozmoderator#433] opened 2024-01-17 09:09 UTC
**Preconditions**
Sign in to Moderator with a non-admin account.

**Steps to reproduce**
1. Access the https://moderator.allizom.org/event/new page.
2. Add some valid data inside the 'Event title' and 'Additional information' fields.
3. Click on the 'save' button.
4. Click on the 'edit' button for the newly created event.

**Expected behavior**
The default moderator (the non-admin account from the preconditions) is displayed/added inside the Moderators field.

**Actual behavior**
The Moderators field is empty.

**Screencasts**
![moderatorRemoved](https://github.com/mozilla/mozmoderator/assets/28087895/d12039f5-51af-4f7a-93a8-2ded8e2e3fed)

**Additional context**
Maybe related to https://github.com/mozilla/mozmoderator/issues/432
This issue is not reproducible if the above steps are performed while signed in with an admin account.

**Comment by akatsoulas** [comment] 2024-02-14 12:41
Closing as duplicate of #437

**Closed by akatsoulas** 2024-02-14 12:41 UTC
